import React from 'react';
import { DollarSign } from 'lucide-react';
import { CrewMember } from '../types';
import { jsPDF } from 'jspdf';
import autoTable from 'jspdf-autotable';

interface FeeSummaryTableProps {
  crew: CrewMember[];
  showId?: number;
}

export default function FeeSummaryTable({ crew, showId }: FeeSummaryTableProps) {
  // Filter out managers and crew without shows
  const crewWithFees = crew.filter(member => {
    const isManager = member.role === 'tour_manager' || member.role === 'production_manager';
    const hasShows = member.shows && member.shows.length > 0;
    const matchesShowFilter = !showId || member.shows?.some(show => show.name.includes(showId.toString()));
    
    return !isManager && hasShows && matchesShowFilter;
  });

  const formatCurrency = (amount: number | undefined) => {
    if (amount === undefined) return 'N/A';
    return new Intl.NumberFormat('en-US', {
      style: 'currency',
      currency: 'USD',
      minimumFractionDigits: 0,
      maximumFractionDigits: 0
    }).format(amount);
  };

  const calculateTotalFees = () => {
    return crewWithFees.reduce((total, member) => {
      const memberTotal = member.shows?.reduce((sum, show) => {
        // If filtering by show, only include matching shows
        if (showId && !show.name.includes(showId.toString())) return sum;
        return sum + (show.fee || 0);
      }, 0) || 0;
      
      return total + memberTotal;
    }, 0);
  };

  const exportFeesReport = () => {
    const doc = new jsPDF();
    
    // Add title
    doc.setFontSize(20);
    doc.setFont('helvetica', 'bold');
    doc.text('Personnel Fees Report', 105, 20, { align: 'center' });
    
    // Add generation date
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text(`Generated on ${new Date().toLocaleDateString()}`, 105, 30, { align: 'center' });
    
    // Create data for the table
    const tableData = crewWithFees.flatMap(member => 
      member.shows?.filter(show => !showId || show.name.includes(showId.toString()))
        .map(show => [
          member.name,
          member.role.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' '),
          show.name,
          show.date,
          show.status,
          show.fee ? `$${show.fee}` : 'N/A'
        ]) || []
    );
    
    // Add the table
    autoTable(doc, {
      startY: 40,
      head: [['Name', 'Role', 'Show', 'Date', 'Status', 'Fee']],
      body: tableData,
      theme: 'striped',
      headStyles: { fillColor: [165, 138, 103], textColor: [255, 255, 255] },
      styles: { fontSize: 8 },
    });
    
    // Add summary
    const summaryY = (doc as any).lastAutoTable.finalY + 15;
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text('Fee Summary by Personnel', 14, summaryY);
    
    const summaryData = crewWithFees.map(member => {
      const relevantShows = member.shows?.filter(show => !showId || show.name.includes(showId.toString())) || [];
      const totalFee = relevantShows.reduce((sum, show) => sum + (show.fee || 0), 0);
      
      return [
        member.name,
        member.role.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' '),
        relevantShows.length,
        `$${totalFee}`
      ];
    });
    
    autoTable(doc, {
      startY: summaryY + 5,
      head: [['Name', 'Role', 'Show Count', 'Total Fees']],
      body: summaryData,
      theme: 'striped',
      headStyles: { fillColor: [165, 138, 103], textColor: [255, 255, 255] },
      styles: { fontSize: 8 },
    });
    
    // Add grand total
    const totalY = (doc as any).lastAutoTable.finalY + 10;
    doc.setFontSize(12);
    doc.setFont('helvetica', 'bold');
    doc.text(`Grand Total: $${calculateTotalFees()}`, 170, totalY, { align: 'right' });
    
    // Add footer
    const pageCount = doc.internal.getNumberOfPages();
    doc.setFontSize(8);
    for (let i = 1; i <= pageCount; i++) {
      doc.setPage(i);
      doc.setTextColor(128, 128, 128);
      doc.text(
        'Generated by THE MANAGER',
        doc.internal.pageSize.width / 2,
        doc.internal.pageSize.height - 10,
        { align: 'center' }
      );
      doc.text(
        `Page ${i} of ${pageCount}`,
        doc.internal.pageSize.width - 20,
        doc.internal.pageSize.height - 10,
        { align: 'right' }
      );
    }
    
    doc.save('personnel_fees_report.pdf');
  };

  if (crewWithFees.length === 0) {
    return (
      <div className="bg-white rounded-lg shadow-md p-6 text-center">
        <p className="text-gray-500">No personnel with fees found</p>
      </div>
    );
  }

  return (
    <div className="bg-white rounded-lg shadow-md overflow-hidden">
      <div className="p-6 border-b border-gray-200 flex justify-between items-center">
        <h2 className="text-lg font-medium text-charcoal uppercase">Personnel Fees Summary</h2>
        <button
          onClick={exportFeesReport}
          className="flex items-center gap-2 px-3 py-1.5 text-sm font-medium text-white bg-primary rounded-md hover:bg-primary"
        >
          <img src="/TM-Download-negro.svg" className="pxi-md icon-white" alt="" />
          Export Report
        </button>
      </div>
      
      <div className="overflow-x-auto">
        <table className="min-w-full divide-y divide-gray-200">
          <thead className="bg-gray-50">
            <tr>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Name
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Role
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Standard Fee
              </th>
              <th scope="col" className="px-6 py-3 text-left text-xs font-medium text-gray-500 uppercase tracking-wider">
                Shows
              </th>
              <th scope="col" className="px-6 py-3 text-right text-xs font-medium text-gray-500 uppercase tracking-wider">
                Total Fees
              </th>
            </tr>
          </thead>
          <tbody className="bg-white divide-y divide-gray-200">
            {crewWithFees.map((member) => {
              const relevantShows = member.shows?.filter(show => !showId || show.name.includes(showId.toString())) || [];
              const totalFees = relevantShows.reduce((sum, show) => sum + (show.fee || 0), 0);
              
              return (
                <tr key={member.id} className="hover:bg-gray-50">
                  <td className="px-6 py-4 whitespace-nowrap text-sm font-medium text-charcoal">
                    {member.name}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {member.role.split('_').map(word => word.charAt(0).toUpperCase() + word.slice(1)).join(' ')}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {member.standardFee ? formatCurrency(member.standardFee) : 'Not set'}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-gray-500">
                    {relevantShows.length}
                  </td>
                  <td className="px-6 py-4 whitespace-nowrap text-sm text-right font-medium text-black">
                    {formatCurrency(totalFees)}
                  </td>
                </tr>
              );
            })}
          </tbody>
          <tfoot className="bg-gray-50">
            <tr>
              <td colSpan={4} className="px-6 py-4 whitespace-nowrap text-sm font-medium text-gray-900 text-right">
                Grand Total:
              </td>
              <td className="px-6 py-4 whitespace-nowrap text-sm font-bold text-right text-black">
                {formatCurrency(calculateTotalFees())}
              </td>
            </tr>
          </tfoot>
        </table>
      </div>
    </div>
  );
}